# src/video/config/constants.py
"""Constants shared across video configuration modules."""

# TTS Configuration
TTS_SPEAKING_RATE_MIN = 0.25
TTS_SPEAKING_RATE_MAX = 4.0
TTS_PITCH_MIN = -20.0
TTS_PITCH_MAX = 20.0

# LLM Configuration
LLM_MAX_TOKENS = 350
LLM_TEMPERATURE = 0.7
LLM_TIMEOUT_SECONDS = 90
LLM_MODEL_FETCH_TIMEOUT_SEC = 15
LLM_RETRY_MULTIPLIER = 1
LLM_RETRY_MIN_WAIT_SEC = 2
LLM_RETRY_MAX_WAIT_SEC = 30
LLM_RETRY_ATTEMPTS = 5

# Font Configuration
FONT_FILE_EXTENSIONS = [".ttf", ".otf"]
FONT_REGULAR_SUFFIXES = ["-regular", "-r"]
DEFAULT_FALLBACK_FONT = "Arial"
FALLBACK_FONT_ALTERNATIVES = ["Montserrat", "Rubik", "Poppins", "Gabarito"]

# SRT Subtitle Format Constants
SRT_TIME_SEPARATOR = " --> "
SRT_BLOCK_SEPARATOR = "\n\n"
SRT_MIN_BLOCK_LINES = 3
SRT_TIME_HOUR_SEPARATOR = ":"
SRT_TIME_MINUTE_SEPARATOR = ":"
SRT_TIME_SECOND_SEPARATOR = ","
SRT_HOURS_IN_SECONDS = 3600
SRT_MINUTES_IN_SECONDS = 60
SRT_MILLISECONDS_DIVISOR = 1000
SRT_LINE_IDENTIFIER = "-->"
SRT_ENCODING = "utf-8"

# Text Processing Patterns
TEXT_NORMALIZATION_PATTERN = r"[^\w\s]"
TEXT_WHITESPACE_PATTERN = r"\s+"
TEXT_WHITESPACE_REPLACEMENT = " "

# ASS Subtitle Format Constants
ASS_COLOR_PATTERN = r"&H(?:(\w{2}))?(\w{2})(\w{2})(\w{2})"
ASS_DEFAULT_ALPHA = "00"
RGB_HEX_FORMAT = "0x{red}{green}{blue}"
RGB_OPACITY_FORMAT = "{rgb_hex}@{opacity:.2f}"
FULL_OPACITY_THRESHOLD = 0.99

# Whisper STT Configuration
DEFAULT_WHISPER_MODEL_DIR = "~/.cache/whisper_models"
WHISPER_WORD_LEVEL_TIMING_MIN_CONFIDENCE = 0.5
WHISPER_MIN_SEGMENT_DURATION_SEC = 0.1
WHISPER_MAX_SEGMENT_DURATION_SEC = 5.0
WHISPER_MIN_WORDS_PER_SEGMENT = 3
WHISPER_MAX_WORDS_PER_SEGMENT = 10
WHISPER_MAX_CHARS_PER_LINE = 42
WHISPER_MIN_SEGMENT_GAP_SEC = 0.1

# Video Assembler Configuration
ASSEMBLER_DEFAULT_MAX_CHARS_PER_LINE = 20
ASSEMBLER_SUBTITLE_BOX_BORDER_WIDTH = 5
ASSEMBLER_IMAGE_LOOP = 1
ASSEMBLER_PAD_COLOR = "black"

# Freesound API Configuration
FREESOUND_DEFAULT_MAX_RESULTS = 15
FREESOUND_DEFAULT_SEARCH_TIMEOUT_SEC = 10
FREESOUND_DEFAULT_DOWNLOAD_TIMEOUT_SEC = 60
FREESOUND_TOKEN_EXPIRY_SEC = 3600
FREESOUND_TOKEN_REFRESH_BUFFER_SEC = 60
FREESOUND_DOWNLOAD_CHUNK_SIZE = 8192 * 4

# Download Configuration
DOWNLOAD_DEFAULT_TIMEOUT_SEC = 30
DOWNLOAD_RETRY_ATTEMPTS = 3
DOWNLOAD_RETRY_MIN_WAIT_SEC = 2
DOWNLOAD_RETRY_MAX_WAIT_SEC = 10

# Subtitle Positioning
SUBTITLE_FALLBACK_SPACING_PERCENT = 0.02
