name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure settings '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, logs, etc.)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ContentEngineAI Version
      description: What version of ContentEngineAI are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu/Debian
        - CentOS/RHEL/Fedora
        - macOS
        - Windows
        - Other (please specify in additional info)
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12.0"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files or settings (remove sensitive information)
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant log output (remove sensitive information)
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, related issues, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using a supported Python version (3.12+)
          required: true
        - label: I have included all requested information above
          required: true