name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Describe the feature in 1-2 sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: As a user, I want to... so that I can...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution or implementation
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: I've also considered...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of ContentEngineAI would this feature affect?
      options:
        - Scraper (Amazon, web scraping)
        - Video Producer (pipeline, processing)
        - AI Services (script generation, TTS, STT)
        - Configuration (settings, YAML)
        - Performance (optimization, monitoring)
        - Documentation (guides, examples)
        - Testing (test suite, quality)
        - CLI/UX (command line interface)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my use of ContentEngineAI
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Detailed Use Case
      description: Provide a detailed example of how you would use this feature
      placeholder: |
        1. I would configure...
        2. Then I would run...
        3. The expected output would be...

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: Any examples, mockups, or references that illustrate your idea
      placeholder: Links to similar implementations, mockups, or detailed examples...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: This could be implemented by...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about the feature request

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
        - label: This feature aligns with ContentEngineAI's goal of automated video production
          required: true
        - label: I have provided sufficient detail for the maintainers to understand the request
          required: true