"""Data models for video publishing and scheduling.

This module defines the core data structures used across all publisher
implementations, providing type-safe representations of publish results,
metadata, configuration, and batch summaries.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any


class PublishStatus(Enum):
    """Status of a publishing operation."""

    PENDING = "pending"
    UPLOADING = "uploading"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    FAILED = "failed"


class Platform(Enum):
    """Supported social media platforms."""

    YOUTUBE = "youtube"
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    TWITTER = "twitter"
    LINKEDIN = "linkedin"


@dataclass(frozen=True)
class PublishResult:
    """Result of a video publishing operation.

    This immutable data structure represents the outcome of publishing a video
    to one or more social media platforms via a scheduling service.

    Attributes
    ----------
        post_id: Unique identifier assigned by the publishing provider
        status: Current status of the post (scheduled, published, failed, etc.)
        platforms: List of platforms the post was published to
        scheduled_time: When the post is scheduled to go live (None if immediate)
        published_urls: List of direct URLs to published posts (empty if scheduled)
        error_message: Error description if status is FAILED (None otherwise)
        metadata: Additional provider-specific data

    """

    post_id: str
    status: PublishStatus
    platforms: tuple[Platform, ...]
    scheduled_time: datetime | None = None
    published_urls: tuple[str, ...] = field(default_factory=tuple)
    error_message: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Post-initialization validation."""
        # Validate post_id is not empty
        if not self.post_id or not self.post_id.strip():
            raise ValueError("post_id cannot be empty")

        # Validate platforms list is not empty
        if not self.platforms:
            raise ValueError("platforms cannot be empty")

        # Validate scheduled_time is not in the past (if provided)
        if self.scheduled_time and self.scheduled_time < datetime.now(
            self.scheduled_time.tzinfo
        ):
            raise ValueError("scheduled_time cannot be in the past")

        # Validate error_message is provided for FAILED status
        if self.status == PublishStatus.FAILED and not self.error_message:
            raise ValueError("error_message required when status is FAILED")

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization.

        Returns
        -------
            Dictionary representation with serializable values

        """
        return {
            "post_id": self.post_id,
            "status": self.status.value,
            "platforms": [p.value for p in self.platforms],
            "scheduled_time": (
                self.scheduled_time.isoformat() if self.scheduled_time else None
            ),
            "published_urls": list(self.published_urls),
            "error_message": self.error_message,
            "metadata": self.metadata,
        }


@dataclass
class PublishMetadata:
    """Platform-specific metadata for video publishing.

    Contains the content and metadata needed to create a post on social media
    platforms. This data is typically loaded from platform-optimized metadata
    files generated by the AI system (v0.17.0+).

    Attributes
    ----------
        platform: Target social media platform
        title: Video title (YouTube only, None for other platforms)
        description: Full description or caption text
        hashtags: List of hashtags (without # prefix)
        keywords: List of keywords for platform algorithms
        character_counts: Character counts for validation

    """

    platform: Platform
    title: str | None
    description: str
    hashtags: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)
    character_counts: dict[str, int] = field(default_factory=dict)

    def __post_init__(self):
        """Post-initialization validation and normalization."""
        # Validate description is not empty
        if not self.description or not self.description.strip():
            raise ValueError(f"description cannot be empty for {self.platform.value}")

        # Validate YouTube has title
        if self.platform == Platform.YOUTUBE and not self.title:
            raise ValueError("YouTube posts require a title")

        # Normalize hashtags (remove # prefix if present)
        self.hashtags = [
            tag.lstrip("#") if tag.startswith("#") else tag for tag in self.hashtags
        ]

        # Calculate character counts if not provided
        if not self.character_counts:
            self.character_counts = {"description": len(self.description)}
            if self.title:
                self.character_counts["title"] = len(self.title)

    def validate_limits(self) -> tuple[bool, str]:
        """Validate content against platform-specific character limits.

        Returns
        -------
            Tuple of (is_valid, error_message)
                - is_valid: True if all limits respected
                - error_message: Empty string if valid, detailed error if invalid

        """
        limits = {
            Platform.YOUTUBE: {"title": 100, "description": 5000, "hashtags": (3, 15)},
            Platform.TIKTOK: {"description": 150, "hashtags": (3, 5)},
            Platform.INSTAGRAM: {"description": 2200, "hashtags": (5, 30)},
        }

        platform_limits = limits.get(self.platform)
        if not platform_limits:
            return True, ""

        # Validate title length (YouTube only)
        if "title" in platform_limits and self.title:
            max_title = platform_limits["title"]
            if len(self.title) > max_title:
                return (
                    False,
                    f"Title exceeds {max_title} chars (got {len(self.title)})",
                )

        # Validate description length
        if "description" in platform_limits:
            max_desc = platform_limits["description"]
            if len(self.description) > max_desc:
                return (
                    False,
                    f"Description exceeds {max_desc} chars (got {len(self.description)})",
                )

        # Validate hashtag count
        if "hashtags" in platform_limits and self.hashtags:
            min_tags, max_tags = platform_limits["hashtags"]
            tag_count = len(self.hashtags)
            if tag_count < min_tags:
                return False, f"Need at least {min_tags} hashtags (got {tag_count})"
            if tag_count > max_tags:
                return False, f"Max {max_tags} hashtags allowed (got {tag_count})"

        return True, ""

    def format_content(self) -> str:
        """Format content for posting (title + description + hashtags).

        Returns
        -------
            Formatted content string ready for publishing

        """
        parts = []

        if self.title and self.platform == Platform.YOUTUBE:
            parts.append(self.title)

        parts.append(self.description)

        if self.hashtags:
            hashtag_str = " ".join(f"#{tag}" for tag in self.hashtags)
            parts.append(hashtag_str)

        return "\n\n".join(parts)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization.

        Returns
        -------
            Dictionary representation with serializable values

        """
        return {
            "platform": self.platform.value,
            "title": self.title,
            "description": self.description,
            "hashtags": self.hashtags,
            "keywords": self.keywords,
            "character_counts": self.character_counts,
        }


@dataclass
class PublisherConfig:
    """Configuration for publisher behavior and credentials.

    This configuration is loaded using three-tier precedence:
    CLI arguments > environment variables > YAML config file

    Attributes
    ----------
        provider: Publishing service to use (late, buffer, etc.)
        api_key: API key for the publishing service
        vercel_token: Vercel token for large file uploads (Late.dev specific)
        default_platforms: Default platforms to publish to if not specified
        immediate_publish: Publish immediately vs scheduled
        privacy_settings: Platform-specific privacy levels
        max_retries: Maximum retry attempts for failed operations
        timeout: Request timeout in seconds
        backoff_multiplier: Exponential backoff multiplier for retries
        stagger_delay_min: Minimum delay between batch posts (seconds)
        stagger_delay_max: Maximum delay between batch posts (seconds)

    """

    provider: str
    api_key: str
    vercel_token: str | None = None
    default_platforms: list[Platform] = field(default_factory=list)
    immediate_publish: bool = True
    privacy_settings: dict[Platform, str] = field(default_factory=dict)
    max_retries: int = 3
    timeout: float = 30.0
    backoff_multiplier: float = 2.0
    stagger_delay_min: int = 30
    stagger_delay_max: int = 60

    def __post_init__(self):
        """Post-initialization validation."""
        # Validate provider
        if not self.provider or not self.provider.strip():
            raise ValueError("provider cannot be empty")

        # Validate API key
        if not self.api_key or not self.api_key.strip():
            raise ValueError("api_key cannot be empty")

        # Validate numeric constraints
        if self.max_retries < 0:
            raise ValueError("max_retries must be non-negative")
        if self.timeout <= 0:
            raise ValueError("timeout must be positive")
        if self.backoff_multiplier <= 1.0:
            raise ValueError("backoff_multiplier must be > 1.0")
        if self.stagger_delay_min < 0:
            raise ValueError("stagger_delay_min must be non-negative")
        if self.stagger_delay_max < self.stagger_delay_min:
            raise ValueError("stagger_delay_max must be >= stagger_delay_min")

        # Set default platforms if empty
        if not self.default_platforms:
            self.default_platforms = [
                Platform.YOUTUBE,
                Platform.TIKTOK,
                Platform.INSTAGRAM,
            ]

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization.

        Returns
        -------
            Dictionary representation (excludes sensitive credentials)

        """
        return {
            "provider": self.provider,
            "api_key": f"{self.api_key[:4]}..." if self.api_key else None,
            "vercel_token": (
                f"{self.vercel_token[:4]}..." if self.vercel_token else None
            ),
            "default_platforms": [p.value for p in self.default_platforms],
            "immediate_publish": self.immediate_publish,
            "privacy_settings": {p.value: v for p, v in self.privacy_settings.items()},
            "max_retries": self.max_retries,
            "timeout": self.timeout,
            "backoff_multiplier": self.backoff_multiplier,
            "stagger_delay_min": self.stagger_delay_min,
            "stagger_delay_max": self.stagger_delay_max,
        }


@dataclass
class BatchPublishSummary:
    """Summary report of batch publishing operation.

    Provides comprehensive overview of batch publishing results including
    success/failure counts per platform and detailed error information.

    Attributes
    ----------
        total_videos: Total number of videos processed
        successful: Number of successfully published/scheduled videos
        failed: Number of failed publishes
        skipped: Number of skipped videos (e.g., missing metadata)
        platform_results: Per-platform success/fail counts
        errors: List of error messages with video identifiers
        duration_seconds: Total batch processing time

    """

    total_videos: int
    successful: int
    failed: int
    skipped: int
    platform_results: dict[Platform, dict[str, int]] = field(default_factory=dict)
    errors: list[dict[str, str]] = field(default_factory=list)
    duration_seconds: float = 0.0

    def __post_init__(self):
        """Post-initialization validation."""
        # Validate counts are non-negative
        if self.total_videos < 0:
            raise ValueError("total_videos must be non-negative")
        if self.successful < 0:
            raise ValueError("successful must be non-negative")
        if self.failed < 0:
            raise ValueError("failed must be non-negative")
        if self.skipped < 0:
            raise ValueError("skipped must be non-negative")

        # Validate total matches sum of outcomes
        if self.total_videos != (self.successful + self.failed + self.skipped):
            raise ValueError(
                "total_videos must equal sum of successful + failed + skipped"
            )

    def add_platform_result(self, platform: Platform, success: bool):
        """Add a result for a specific platform.

        Args:
        ----
            platform: Platform that was published to
            success: Whether the publish succeeded

        """
        if platform not in self.platform_results:
            self.platform_results[platform] = {"successful": 0, "failed": 0}

        if success:
            self.platform_results[platform]["successful"] += 1
        else:
            self.platform_results[platform]["failed"] += 1

    def add_error(self, video_id: str, error_message: str):
        """Add an error to the summary.

        Args:
        ----
            video_id: Identifier of the video that failed
            error_message: Description of the error

        """
        self.errors.append({"video_id": video_id, "error": error_message})

    def get_success_rate(self) -> float:
        """Calculate overall success rate.

        Returns
        -------
            Success rate as percentage (0.0 to 100.0)

        """
        if self.total_videos == 0:
            return 0.0
        return (self.successful / self.total_videos) * 100.0

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization.

        Returns
        -------
            Dictionary representation with all summary data

        """
        return {
            "total_videos": self.total_videos,
            "successful": self.successful,
            "failed": self.failed,
            "skipped": self.skipped,
            "success_rate": f"{self.get_success_rate():.1f}%",
            "platform_results": {
                p.value: counts for p, counts in self.platform_results.items()
            },
            "errors": self.errors,
            "duration_seconds": self.duration_seconds,
        }
